baseURL       = "https://igem.berkeley.edu/"
languageCode  = "en-us"
title         = "iGEM at Berkeley"
theme         = "roxo"
summarylength = 10

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 1
  [[menu.nav]]
    name    = "Members"
    url     = "members"
    weight  = 2
  [[menu.nav]]
    name    = "Eternals"
    url     = "eternals"
    weight  = 3
  [[menu.nav]]
    name    = "Finance"
    url     = "finance"
    weight  = 4
  [[menu.nav]]
    name    = "Teams"
    url     = "teams"
    weight  = 5
  [[menu.nav]]
    name    = "DeCal"
    url     = "ferb"
    weight  = 6
  [[menu.nav]]
    name    = "Join iGEM"
    url     = "apply"
    weight  = 7

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "iGEM at Berkeley"
  author = "iGEM at Berkeley"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/myykjpje"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "First Name"
    placeholder_last_name         = "Last Name"
    placeholder_email             = "Email"
    placeholder_project_type      = "Project Type"
    placeholder_about_the_project = "About the Project"
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      value = "gd"
      title  = "Graphics Design"
    [[params.contactForm.projectType]]
      value = "wd"
      title  = "Web Design"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Join Us"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/retreat.png"
    heading               = "Join us for undergrad-led synthetic biology research, training programs, and a large community of aspiring scientists!"
    tagline               = "iGEM at Berkeley"
    primary_button        = "Apply to join iGEM"
    primary_button_url    = "/apply"
    secondary_button      = "General Member Form"
    secondary_button_url  = "https://docs.google.com/forms/d/e/1FAIpQLSdf3GZ4lHacONnspn08-ca_0arWuRrSkgVZHPoelU54fwIz5A/viewform"
    tertiary_button      = "Contact us on Instagram"
    tertiary_button_url  = "https://www.instagram.com/igematberkeley/"

  [params.portfolio]
    enable    = true
    title     = "OUR TEAMS"
    subtitle  = "Take a look at our Wetlab and Computational Biology teams."

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "APPLY NOW"
    primary_button      = "Apply to an iGEM team"
    primary_button_url  = "https://forms.gle/c4TgnW8mzwJ5iUWt8"
    secondary_button    = "Apply to our DeCals"
    secondary_button_url = "http://linktr.ee/igematberkeleydecals"
    tertiary_button    = "View All Applications"
    tertiary_button_url = "http://linktr.ee/igematberkeley"
    finance_primary_button      = "Join Our Team"
    finance_primary_button_url  = "finance-join-our-team"
    finance_secondary_button    = "Be A Partner"
    finance_secondary_button_url = "finance-be-a-partner"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Us"
      address = "University of California, Berkeley"
      phone   = "directors@igem.berkeley.edu"
      email   = ""
      # Footer Site Map
      [params.footer.sitemap]
        title   = "Site Map"
        [[params.footer.sitemap.link]]
          name = "About"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Community"
          url  = "community"
        [[params.footer.sitemap.link]]
          name = "Eternals"
          url  = "eternals"
        [[params.footer.sitemap.link]]
          name = "Finance"
          url  = "finance"
        [[params.footer.sitemap.link]]
          name = "Project Teams"
          url  = "teams"
        [[params.footer.sitemap.link]]
          name = "CUBS"
          url  = "cubs"
        [[params.footer.sitemap.link]]
          name = "DeCal"
          url  = "ferb"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "https://www.instagram.com/igematberkeley"
        [[params.footer.social.link]]
          name = "Facebook"
          url  = "https://www.facebook.com/igematberk/"
        [[params.footer.social.link]]
          name = "Twitter"
          url  = "https://twitter.com/igematberkeley"
        [[params.footer.social.link]]
          name = "GitHub"
          url  = "https://github.com/igematberkeley"
      # Footer Sponsor
      [params.footer.sponsor]
        title       = "Thank You to Our Sponsors:"
        description = "<a href='http://mcb.berkeley.edu/labs/botchan/'>Botchan Lab</a> | Rulison Family | Tonkomo LLC | Pande Family | Spiegel Family | Jacob Pruess | Kanjana Taedullayasatit | Stuart Russell | Sophie Hahn | Lin Tan | <a href='https://www.geneious.com'>Geneious</a>"
      # Footer Service
      [params.footer.service]
        title       = "Student Group Disclaimer:"
        description = "We are a student group acting independently of the University of California. We take full responsibility for our organization and this web site."
      
        
